name: skywatch
description: SkyWatch.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  bloc_test: ^9.0.3
  get_it: ^7.6.4
  permission_handler: ^11.0.1
  path_provider: ^2.1.1
  geolocator: ^10.1.0
  dio: ^5.3.3
  dartz: ^0.10.1
  equatable: ^2.0.5
  meta: ^1.9.1
  shimmer: ^3.0.0
  image_picker: ^1.0.4
  flutter_speed_dial: ^7.0.0
  video_player: ^2.7.2
  chewie: ^1.7.1
  mocktail: ^1.0.1
  http_mock_adapter: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/gifs/
    - assets/icons/
    - assets/icons/weather/
    - assets/icons/weather/day/
    - assets/icons/weather/night/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600